# netlify.toml

[functions]
  directory = ".netlify/functions"
  # Pastikan ini ada untuk memberitahu Netlify menggunakan runtime Python untuk fungsi-fungsi di direktori tersebut.
  node_bundler = "esbuild"
  environment = { PYTHON_VERSION = "3.9" } # Opsional: Anda bisa coba "3.10" atau "3.11" jika mau.

