# netlify.toml

[build]
  command = "echo 'Starting build...'" # Perintah dummy, bisa juga "ls"
  publish = "/" # Direktori publish (opsional, defaultnya root)

[functions]
  directory = ".netlify/functions"
  environment = { PYTHON_VERSION = "3.9" }

